### ISSUE TITLE
semi automatic update for /pkgs

### ISSUE THREAD

**Issue by benneti** [divnix/devos#118]
**Is your feature request related to a problem? Please describe.**
I do not want to check manually whether my custom pkgs have updates.

**Describe the solution you'd like**
Add https://github.com/ryantm/nixpkgs-update to the configuration and maybe a litte subcommand to flk to have a simple interface to it (I plan to try it myself when I have some more time).

**Comment by benneti** [comment]
I just tried out nixpkgs-update and I think that I neither fully understand how to use it nor that it does exactly what we would need to.

**Comment by nrdxp** [comment]
This is a problem flakes could actually [solve](https://discourse.nixos.org/t/possibility-for-subflakes/11589) for us. We could do it right now, I just don't want to flood the inputs with a huge list of package sources, which is why I started that dicussion. 

Although I guess, if it's only in the community branch, it wouldn't be horrible, if we have to.

**Comment by benneti** [comment]
thats actually a super cool idea.
A small down side would be that (as far as I understand it) it would only work with git repositories (i.e. not with binary releases).

**Comment by nrdxp** [comment]
IIRC, flakes now have a mercurial backend, as well as the ability to simply point to an https url with a tarball. So I think binary should be possible, you just have to handle the input differently.

**Comment by benneti** [comment]
this sounds better and better!
