### ISSUE TITLE
Expected that not all packages are exported?

### ISSUE THREAD

**Issue by mohe2015** [divnix/devos#151]
## Expected Behavior
```
nix build /etc/nixos#openjdk15
```
should build or download the package from cache.

## Current Behavior
```
nix build /etc/nixos#openjdk15
warning: Git tree '/etc/nixos' is dirty
error: --- Error --------------------------------------------------------------------------------------------------------------------------------------- nix
flake 'git+file:///etc/nixos' does not provide attribute 'packages.x86_64-linux.openjdk15', 'legacyPackages.x86_64-linux.openjdk15' or 'openjdk15'
```

## Steps to Reproduce
1. `nix build /etc/nixos#openjdk15`

## Context
I got used to this from nixpkgs so I thought it would make sense here too.

Is there a similar command?

**Comment by Pacman99** [comment]
I'm getting this too. Some of my packages work, but one or two don't. I can't seem to figure out what the difference in the ones that aren't found. The packages build and evaluate fine with just nix-build.

**Comment by nrdxp** [comment]
@mohe2015 Are you saying we should output all of nixpkgs, overlays applied, [like we used to]( https://github.com/divnix/devos/commit/1b8080651684a889c028653e7f8b55cd6db80aa0#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R91).

I figured this was kinda overkill since nixpkgs was readily available and we might want to use legacyPackages for other things, such as the hmModules we are currently using it for. Maybe we could define out own custom output `pkgs` and install packages `nix build "/etc/nixos#pkgs.openjdk`.

The main question is, what is the main benefit of this over just installing from nixpkgs, since nixpkgs is pinned in the devos nix registry by default already to save a network pull. Packages we modify with an overlay are exported.

> I'm getting this too. Some of my packages work, but one or two don't. I can't seem to figure out what the difference in the ones that aren't found. The packages build and evaluate fine with just nix-build.

@Pacman99, I think you're referring to a slightly different issue with the call to [flattenTreeSystem](https://github.com/numtide/flake-utils/pull/13#issuecomment-786297109), which can have strange behavior. Indeed we are going to have to replace this anyway, since it didn't make it to upstream flake-utils and the branch will probably get deleted at some point.

**Comment by mohe2015** [comment]
@nrdxp I mainly wondered why it didn't work because I was pretty sure it for in the past. But the current behavior is fine to me. I also had some strange case where a package didn't build  (jitsi-videobridge in the service module) but for some reason building jitsi-videobridge itself did work. But I assume this does not have anything to do with nixflk (maybe I was just too tired or whatever, will check again today).

I will close this issue then. Thanks for explaining!
