### ISSUE TITLE
All suites return "attribute missing"

### ISSUE THREAD

**Issue by ymarkus** [divnix/devos#282]
After pulling the latest commits from the core branch, all my suites defined in `profiles/suites.nix` return an "attribute missing error".

## Current Behavior
`hosts/whatever.nix`:
```nix
{ hardware, suites, ... }:

{
  imports = [
    ./whatever/hardware.nix
    hardware.whatever
  ] ++ suites.laptop ++ suites.gaming ++ suites.virt;
  [...]
}
```

trying to build it:
```
❯ sudo nixos-rebuild --flake ".#whatever" boot
building the system configuration...
error: attribute 'laptop' missing

       at /nix/store/ls9kilcc14yxbci68xmaxn67ww6n6j7l-source/hosts/whatever.nix:7:8:

            6|     hardware.whatever
            7|   ] ++ suites.laptop ++ suites.gaming ++ suites.virt;
             |        ^
            8|
(use '--show-trace' to show detailed location information)
```

## Possible Solution
There seems to be a `suites` definition in `default.nix` now, is that supposed to be used from now on? ~Then the documentation has to be updated!~
OK, it seems the documentation does say to use the namespaces for `nixos` and `home`, but the issue there is that you can't use `rec` and that makes it quite messy.

## Steps to Reproduce
1. Define suites in `profile/suites.nix`
2. Try to use those suites in host

**Comment by blaggacao** [comment]
We recently did quite a big refactoring in order to navigate the whole project into less choppy future waters.

On behalf of the involved parties, I apologize for the troubles caused.

Suites where such a "shallow" consolidation that, in order to provide a better overview of a particular devos environment, we decided to define them directly in `flake.nix`.

Of course, they can be kept in their own file, but the suite's function signature has to mirror the files fed to profiles from now on. That is true for both subsystems, where suites are in use: `home` & `nixos`.

Example following...

**Comment by Pacman99** [comment]
> the issue there is that you can't use rec and that makes it quite messy.

I'm pretty sure you can use rec. I use it in my repo. Was there an issue why you used it? We should probably add rec to the flake.nix.

**Comment by ymarkus** [comment]
@blaggacao Thanks for the detailed explanation. I actually like the changes you're implementing, that's why I pull them into my repo! I just think the documentation could have a little more information. I'll have a look at adding it.


> I'm pretty sure you can use `rec`. I use it in my repo. Was there an issue when you used it? We should probably add rec to the flake.nix.
If I try to use it this way: 
```nix
suites = { profiles, users, ... }: with profiles; rec {
[...]
};
```
I get: 
```
❯ sudo nixos-rebuild --flake ".#whatever" boot
building the system configuration...
error: infinite recursion encountered

       at /nix/store/8xvwfm02dicgbpkyyaqi0961nd01r8g0-source/lib/modules.nix:305:28:

          304|         builtins.addErrorContext (context name)
          305|           (args.${name} or config._module.args.${name})
             |                            ^
          306|       ) (lib.functionArgs f);
(use '--show-trace' to show detailed location information)
```

**Comment by Pacman99** [comment]
Ohh that seems to be a different problem. It looks to be a module system infinite recursion error. That is usually unrelated to `rec`. Can you post the full stack trace, that should help me figure out exactly where it is.

Generally it happens when you try to use a module argument in an `imports` line or you ask for too many arguments in a module. Keep in mind your flake.nix is now a module since that's how we now evaluate arguments passed to digga. So it could be happening somewhere there.

`rec` could be triggering it somehow, but I don't think this error is actually because of `rec`.

**Comment by blaggacao** [comment]
@ymarkus Can you also post your current suites stanza from the _flake.nix_ &mdash; or a minimal example that reproduces the error? Just in case. It might help a little.

**Comment by ymarkus** [comment]
I think I have found the error: my host looks like this:
```nix
{ hardware, suites, ... }:

{
  imports = [
    ./whatever/hardware.nix
    hardware.lenovo-thinkpad-x1-6th-gen
  ] ++ suites.mobileWS ++ suites.gaming ++ suites.virt;
  ...
}
```
If I remove the `hardware` references, it works. I'll move those to the `flake.nix` file. But the documentation is wrong. Where it says: 
```nix
{
  nixos.hosts = mkMerge [
    (devos.lib.importHosts ./hosts)
    {
      librem = {
        channelName = "latest";
        modules = [ hardware.purism-librem-13v3 ];
      };
    }
  ];
}
```
it should rather be: 
```
{
  nixos.hosts = mkMerge [
    (devos.lib.importHosts ./hosts)
    {
      librem = {
        channelName = "latest";
        modules = [ nixos-hardware.nixosModules.purism-librem-13v3 ];
      };
    }
  ];
}
```

**Comment by ymarkus** [comment]
Thanks for your help and sorry to bother. As soon as the documentation is fixed, we can close this!

**Comment by ymarkus** [comment]
Ok, thanks for the help everyone!
