### ISSUE TITLE
Core profile optional (doc)

### ISSUE THREAD

**Issue by blaggacao** [divnix/devos#295]
Let's document via well contextualized code comments how the different parts of `core` are optional.

The only thing that has a drawback would probably be openssh disabled because no host cert is autocreated.

/cc @Radvendii

**Comment by Pacman99** [comment]
I'm going to close this, because the core profile is entirely optional in that you can cleanly delete and there shouldn't be any side effects, it just sets some nice defaults. I would like to leave it in profiles and not have it as a doc, so that it serves as an example for how profiles work and a way for us to collect sane defaults for nixos.
