### ISSUE TITLE
local flake registry freezes NUR input

### ISSUE THREAD

**Issue by lourkeur** [divnix/devos#347]
## Expected Behavior

Running `flk update` on a DevOS machine should update the `nur` input to the tip of the appropriate git branch.

## Current Behavior

`flk update` idempotently converts the input to the equivalent path:/nix/store/xxx-source.

## Possible Solution
Explicitly specify `nur.url = "github:nix-community/nur"`, downside being that it is redundant- and silly-looking as well as fragile.

Altternatively, fix this in a more general way, since this is the second time such an issue occurs (#142) which suggests there's an underlying issue.

## Steps to Reproduce
1. Be on a DevOS based system
2. Try to update any flakes that requires `nur` from the registry
3. Check commit message and contents of `flake.lock`

## Context

I use NUR together with DevOS. I believe based on looking at the code that this issue is still present in `develop`.

## Your Environment

I use a system configuration based on the current tip of `core`. This phenomenon hit me on Friday at [this commit](https://github.com/lourkeur/config/commit/1ac1abc8e51812ab6750375d0193da54fdd2465c) but took me until today to realize.

**Comment by Pacman99** [comment]
This is a side effect of https://github.com/divnix/digga/commit/3d3d6bba608e83abaabb5d5373444d03f7ca9442. Which makes it so that a local flake registry is created from all your inputs. So once you rebuild once and the flake registry gets created the next time you update your inputs they get set to paths in the nix store.

The goal with that commit and the feature in fup is to allow you to easily do `nix shell nur#...` and not have to download the flake. But it creates side effects like this when you use the nix registry. I'm ok with reverting that commit so thats its opt-in. I generally avoid the public nix registry so I like having a local one auto generated, but I understand that its frustrating for others who make use of the registry.

**Comment by lourkeur** [comment]
Absolutely, the custom registry comes handy sometimes. OTOH, when they shadow the normal one it breaks assumptions. Nix has a `--no-registries` flag, but not one that could be used to select the normal registry. Maybe it should have an option for that?

**Comment by blaggacao** [comment]
I agree, we should make this opt-in.

> Nix has a --no-registries flag, but not one that could be used to select the normal registry. Maybe it should have an option for that?

There has been some upstream work recently, let me check if I find it.

**Comment by Pacman99** [comment]
We no longer set the registry by default to all your inputs. Since that feature is now opt-in, I think we can close this.
