### ISSUE TITLE
Changing default branch to 'main'

### ISSUE THREAD

**Issue by Pacman99** [divnix/devos#384]
The default branch for this repository will change to `main` soon instead of `master. 

This is being done for a couple reasons, because git and github are moving towards that standard, 'main' is more descriptive of the branches purpose, and its two letters shorter.

**Comment by nrdxp** [comment]
@Pacman99, I bumped you to admin so you can change the branch name when ready.

Just for the record, and because I need to vent a bit (:sweat_smile:) I am still against it, but I promised that we could take a vote on the matrix channel and this is what was decided. Seems like a bit of a bait and switch sinced it was changed without any consensus _in the first place_, and I merely undid what was done...

However, let nobody say I'm not a man of my word.

**Comment by Pacman99** [comment]
I understand and respect your view on this. So I appreciate you keeping to your word.
I just switched the branch name for this repository.
